### PR TITLE
add run-time and history-write logging for ufs

### PR DESCRIPTION
**Pull request by DeniseWorthen**
Add two types of logging files for use by UFS within the CICE cap:

1) run-time logging to measure performance for UFS. The timing information is written to ``log.ice.timer``. The feature is enabled using a configuration attribute ``RunTimeLog = true``, otherwise no logging will be performed.
2) history-write logging to provide a file for the initiation of post-processing jobs in the global-workflow. The file written for forecast hour HHH is  ``log.ice.fHHH``.

required by  https://github.com/ufs-community/ufs-weather-model/issues/1367
resolves - #57

The logging is added inside ``cice_wrapper_mod`` code, mimicking what is currently done for the perf_mod calls for CESM (``t_startf`` etc).

### CODE REVIEW

**Review by apcraig — APPROVED** [review]
This all looks reasonable to me.  All changes are in the nuopc/cmeps driver, so don't affect CICE in general.  I guess I do wonder whether the CICE timers could have been used rather than creating yet another timer library.  Maybe CICE needs to add some additional flexibility and/or features?

**Comment by DeniseWorthen** [comment]
@apcraig Thanks. We definitely didn't consider the feasibility of using CICE timers here. The approach has been duplicating the same calls w/in all the caps used by UFS so we knew we had the same basic measures in each case.

**Comment by apcraig** [comment]
@DeniseWorthen.  I totally understand.  Another idea would be to have a common set of time methods in some UFS share code?  What's done here is quick, easy, and has limited flexibility.  And I guess it's duplicated in all components.  There are pluses and minuses.  Thanks.

**Review by dabail10 — COMMENTED** [review]
This all looks fine. Do we need some ifdefs here? I see you've added some.

**Comment by DeniseWorthen** [comment]
Hi Dave. Thanks. I've avoided using ifdefs by modifying the cice_wrapper_mod.F90 instead. When compiled with 'ifdef CESMCOUPLED', then the "ufs" calls will just be stubs. I was most worried about uninitialized variables when used w/ CESM, but I did test for how it would work when CEMSCOUPLED was set in the wrapper and it passed our debug compile/run test.

**Review by dabail10 — APPROVED** [review]
Oh, I see. I had not looked at cice_wrapper_mod before. Works for me.

**Pull request closed without merging**
