### PR TITLE
update CICE from Consortium/main

### LINKED ISSUE #58: updates from Consortium/main
PRs merged at Consortium/main need to be added to our local fork. These include:

- An update for the floe-size distribution when wave-cice coupling is enabled (https://github.com/CICE-Consortium/CICE/pull/813). This updates Icepack with a bug fix for lateral melt (https://github.com/CICE-Consortium/Icepack/pull/424). UFS does not currently have a wave-ice coupling test, but this would change answers to any current configuration testing wave-ice coupling.

- An update for added metadata for history files https://github.com/CICE-Consortium/CICE/pull/816

- Minor other updates including
https://github.com/CICE-Consortium/CICE/pull/812
https://github.com/CICE-Consortium/CICE/pull/817
https://github.com/CICE-Consortium/CICE/pull/818
https://github.com/CICE-Consortium/CICE/pull/810
https://github.com/CICE-Consortium/CICE/pull/801
https://github.com/CICE-Consortium/CICE/pull/806
https://github.com/CICE-Consortium/CICE/pull/820

### PR DESCRIPTION
**Pull request by DeniseWorthen**
- fixes #58

### CODE REVIEW

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by NeilBarton-NOAA — APPROVED** [review]

**Comment by zach1221** [comment]
This PR has been reviewed, and all tests are done on PR [#1672](https://github.com/ufs-community/ufs-weather-model/pull/1672). @NeilBarton-NOAA are you able to merge this PR?

**Comment by NeilBarton-NOAA** [comment]
I'm not authorized to merge this. maybe @DeniseWorthen?

**Comment by DeniseWorthen** [comment]
Thanks @NeilBarton-NOAA. 

@zach1221 I'm the code manager for CICE and generally do the merges. I assume we're ready now, right?

**Comment by zach1221** [comment]
@DeniseWorthen, understood. Yes, please proceed to merge this PR.

**Pull request merged**
